using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using photo_history_server.Domain.Entities;

namespace photo_history_server.Infrastructure.Persistence.Configurations;

public class PhotoConfiguration : IEntityTypeConfiguration<Photo>
{
    public void Configure(EntityTypeBuilder<Photo> builder)
    {
        // Primary key – GUID generated by SQL Server on insert
        builder.HasKey(p => p.Id);
        builder.Property(p => p.Id)
            .ValueGeneratedOnAdd();

        builder.Property(p => p.FileName).HasMaxLength(256).IsRequired();
        builder.Property(p => p.FilePath).HasMaxLength(512).IsRequired();
        builder.Property(p => p.OriginalName).HasMaxLength(256).IsRequired();
        builder.Property(p => p.Description).HasMaxLength(1000);

        // Geographic coordinates
        builder.Property(p => p.Latitude).IsRequired();
        builder.Property(p => p.Longitude).IsRequired();

        // Optional fields
        builder.Property(p => p.Address).HasMaxLength(512).IsRequired(false);
        builder.Property(p => p.TakenAt).IsRequired(false);

        builder.HasOne(p => p.User)
            .WithMany()
            .HasForeignKey(p => p.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}

