using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using photo_history_server.Domain.Entities;

namespace photo_history_server.Infrastructure.Persistence.Configurations;

public class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        // Primary key – GUID generated by SQL Server on insert
        builder.HasKey(u => u.Id);
        builder.Property(u => u.Id)
            .ValueGeneratedOnAdd();

        // Email – required, max 256, unique index
        builder.Property(u => u.Email)
            .IsRequired()
            .HasMaxLength(256);
        builder.HasIndex(u => u.Email)
            .IsUnique();

        // Username – required, max 100
        builder.Property(u => u.Username)
            .IsRequired()
            .HasMaxLength(100);

        // Role – stored as string for readability in DB
        builder.Property(u => u.Role)
            .HasConversion<string>();

        // Optional fields
        builder.Property(u => u.PasswordHash).IsRequired(false);
        builder.Property(u => u.GoogleId).IsRequired(false);
        builder.Property(u => u.GitHubId).IsRequired(false);
        builder.Property(u => u.AvatarUrl).IsRequired(false);
    }
}

